export const FETCHING_PITTITION = 'FETCHING_PITTITION'
export const FETCHING_PITTITION_SUCCESS = 'FETCHING_PITTITION_SUCCESS'
export const FETCHING_PITTITION_FAILURE = 'FETCHING_PITTITION_FAILURE'


export const ADDING_PITTITION = 'ADDING_PITTITION'
export const ADDING_PITTITION_SUCCESS = 'ADDING_PITTITION_SUCCESS'
export const ADDING_PITTITION_FAILURE = 'ADDING_PITTITION_FAILURE'

export const LOGGING_IN = 'LOGGING_IN'
export const LOGGING_IN_SUCCESS = 'LOGGING_IN_SUCCESS'
export const LOGGING_IN_FAILURE = 'LOGGING_IN_FAILURE'

export const LOGOUT = "LOGGING_OUT"

export const FETCHING_ACTIVE_PITTITION = 'FETCHING_ACTIVE_PITTITION'

export const ADDING_COMMENT = 'ADDING_COMMENT'
export const ADDING_COMMENT_SUCCESS = 'ADDING_COMMENT_SUCCESS'
export const ADDING_COMMENT_FAILURE = 'ADDING_COMMENT_FAILURE'